"""add user_profile jobs job_applications tables

Revision ID: 7e4f1cd4b5b4
Revises: de73f8c15fcc
Create Date: 2026-06-13 20:40:11.398537
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '7e4f1cd4b5b4'
down_revision: Union[str, None] = 'de73f8c15fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('salary_range', sa.String(length=200), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dream_companies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('resume_ats_score', sa.Float(), nullable=True),
    sa.Column('resume_last_analyzed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('important_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('friends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('family', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('favorite_tech', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('favorite_music', sa.String(length=500), nullable=True),
    sa.Column('favorite_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_hunt_active', sa.Boolean(), nullable=False),
    sa.Column('preferred_work_type', sa.String(length=50), nullable=True),
    sa.Column('expected_salary', sa.String(length=100), nullable=True),
    sa.Column('notice_period', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('job_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_applications_job_id'), 'job_applications', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_applications_user_id'), 'job_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_applications_user_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_applications_job_id'), table_name='job_applications')
    op.drop_table('job_applications')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
