"""
Nidhi — GitHub Agent

Integrates with Github MCP server for repository, issue, pull request, and file management.
"""

from __future__ import annotations

import logging
from langchain_core.messages import AIMessage
from app.agents.state import AgentState

logger = logging.getLogger(__name__)


async def run_github_agent(state: AgentState) -> dict:
    """Run the GitHub agent."""
    messages = state.get("messages", [])
    latest = messages[-1].content if messages else ""

    logger.info(f"GitHub agent processing: {latest[:80]}")

    operation = _parse_github_intent(latest)
    result = await _execute_github_operation(operation, latest)

    return {
        "agent_results": {
            **state.get("agent_results", {}),
            "github_agent": {"response": result, "operation": operation},
        },
        "final_response": result,
        "messages": [AIMessage(content=result)],
    }


def _parse_github_intent(message: str) -> str:
    msg = message.lower()
    if any(w in msg for w in ["repo", "repositories", "list repo", "my repo"]):
        return "list_repos"
    elif any(w in msg for w in ["issue", "create issue", "bug issue"]):
        return "create_issue"
    elif any(w in msg for w in ["pull request", "pr", "create pr"]):
        return "create_pr"
    elif any(w in msg for w in ["get file", "view file", "github file"]):
        return "get_file"
    return "list_repos"


async def _execute_github_operation(operation: str, message: str) -> str:
    """Execute GitHub operations via MCP if enabled, else fall back to mock instructions."""
    from app.config import get_settings
    from app.mcp.client import mcp_manager

    settings = get_settings()
    use_mcp = settings.mcp_github_enabled and bool(settings.github_token)

    if use_mcp:
        try:
            if operation == "list_repos":
                # List repositories
                res = await mcp_manager.call_tool("github", "search_repositories", {"query": "owner:udayrastogi0531", "page": 1})
                content = res.get("content", [])
                if content:
                    return f"🐙 **GitHub Repositories (GitHub MCP):**\n\n{content[0].get('text', '')}"
                return "🐙 No repositories found."
            
            elif operation == "create_issue":
                # Create an issue
                res = await mcp_manager.call_tool("github", "create_issue", {
                    "owner": "udayrastogi0531",
                    "repo": "Agentic-ai-os",
                    "title": f"Issue: {message[:50]}",
                    "body": f"Created automatically by Nidhi.\n\nContext: {message}"
                })
                content = res.get("content", [])
                if content:
                    return f"🐙 **GitHub Issue Created (GitHub MCP):**\n\n{content[0].get('text', '')}"

            elif operation == "create_pr":
                # Create a PR
                res = await mcp_manager.call_tool("github", "create_pull_request", {
                    "owner": "udayrastogi0531",
                    "repo": "Agentic-ai-os",
                    "title": f"PR: {message[:50]}",
                    "head": "feature-branch",
                    "base": "main",
                    "body": "PR generated by Nidhi."
                })
                content = res.get("content", [])
                if content:
                    return f"🐙 **GitHub Pull Request Created (GitHub MCP):**\n\n{content[0].get('text', '')}"
        except Exception as e:
            logger.warning(f"GitHub MCP call failed, using fallback instructions: {e}")

    # Fallback / Setup instructions
    if operation == "list_repos":
        return (
            "🐙 **GitHub Integration**\n\n"
            "To view your GitHub repositories, please connect GitHub in Settings by providing a token.\n\n"
            "Status: GitHub MCP client not configured.\n\n"
            "Capabilities once configured:\n"
            "- List and search repositories\n"
            "- Create and search issues\n"
            "- Create and view pull requests\n"
            "- Read files directly from repository branches"
        )
    elif operation == "create_issue":
        return (
            "🐙 I can create GitHub issues for you!\n\n"
            "Please configure `github_token` and `mcp_github_enabled` in settings.\n"
            "Format when configured: *\"Create a GitHub issue titled 'Fix router loop'\"*"
        )
    elif operation == "create_pr":
        return (
            "🐙 I can create pull requests directly on your repository!\n\n"
            "Please configure the GitHub MCP token in settings to authorize pull request management."
        )
    else:
        return f"🐙 GitHub operation `{operation}` registered. Setup your token in Settings to enable."
