"""
Uday AI — LangGraph Core Graph Wiring
"""

from __future__ import annotations

import logging
from langchain_core.messages import HumanMessage, AIMessage
from langgraph.graph import StateGraph, END

from app.agents.state import AgentState
from app.agents.planner import run_planner
from app.agents.memory import run_memory_node
from app.agents.tools import run_evaluate_node, route_evaluation, run_replan_node
from app.agents.response import run_response_node

# Import specialized sub-agents
from app.agents.file_agent import run_file_agent
from app.agents.task_agent import run_task_agent
from app.agents.notes_agent import run_notes_agent
from app.agents.memory_agent import run_memory_agent
from app.agents.research_agent import run_research_agent
from app.agents.coding_agent import run_coding_agent
from app.agents.browser_agent import run_browser_agent
from app.agents.gmail_agent import run_gmail_agent
from app.agents.calendar_agent import run_calendar_agent
from app.agents.github_agent import run_github_agent

logger = logging.getLogger(__name__)


async def run_voice_agent(state: AgentState) -> dict:
    """Simple agent wrapper for voice commands."""
    plan = state.get("plan", [])
    current_step = state.get("current_step", 0)
    argument = plan[current_step].get("argument", "") if current_step < len(plan) else ""
    return {
        "final_response": f"Voice system command executed: {argument}",
        "messages": [AIMessage(content=f"Voice system command executed: {argument}")]
    }


def make_agent_node(agent_run_fn, tool_name: str):
    """
    High-order wrapper to convert a sub-agent run function into a formal LangGraph node.
    Enforces loop boundaries, safety gate confirmation checks, and step aggregation.
    """
    async def node_fn(state: AgentState) -> dict:
        loop_count = state.get("loop_count", 0) + 1

        if loop_count > 10:
            logger.warning(f"[Node {tool_name}] Autonomous loop count limit (10) exceeded.")
            return {
                "loop_count": loop_count,
                "error": "Autonomous execution limit of 10 loops exceeded.",
                "final_response": "I have paused the execution as the autonomous action loop exceeded the safety limit of 10 steps.",
                "messages": [AIMessage(content="[System Error] Autonomous execution loop count exceeded.")]
            }

        plan = state.get("plan", [])
        current_step = state.get("current_step", 0)

        if not plan or current_step >= len(plan):
            logger.warning(f"[Node {tool_name}] Invalid step index: {current_step}")
            return {
                "current_step": current_step + 1,
                "loop_count": loop_count
            }

        step = plan[current_step]
        argument = step.get("argument", "")

        from app.security.gates import requires_confirmation

        # Check if this tool execution requires confirmation and has not been approved yet
        if requires_confirmation(tool_name, argument) and not state.get("approved"):
            logger.info(f"[Node {tool_name}] Intercepting for confirmation. Argument: '{argument}'")
            return {
                "approval_required": True,
                "loop_count": loop_count
            }

        logger.info(f"[Node {tool_name}] Executing step {current_step + 1}/{len(plan)}: '{tool_name}' with args: '{argument}'")

        # Inject the argument as a HumanMessage at the end of the history
        # so the sub-agents read the correct parameters
        injected_state = state.copy()
        injected_state["messages"] = list(state.get("messages", [])) + [HumanMessage(content=argument)]

        tool_results = state.get("tool_results", {}).copy()

        try:
            result = await agent_run_fn(injected_state)
            
            # Store tool output
            tool_results[tool_name] = result.get("final_response", "")

            # Extract messages generated by the tool
            new_messages = result.get("messages", [])

            # Merge results back into the state updates
            updates = {
                "current_step": current_step + 1,
                "loop_count": loop_count,
                "tool_results": tool_results,
                "approved": False,
                "approval_required": False,
                "agent_results": {
                    **state.get("agent_results", {}),
                    **result.get("agent_results", {})
                }
            }
            if new_messages:
                updates["messages"] = new_messages

            return updates

        except Exception as e:
            logger.error(f"[Node {tool_name}] Error executing agent: {e}", exc_info=True)
            tool_results[tool_name] = f"Error: {str(e)}"
            return {
                "current_step": current_step + 1,
                "loop_count": loop_count,
                "tool_results": tool_results,
                "approved": False,
                "approval_required": False,
                "error": f"Agent '{tool_name}' failed: {str(e)}"
            }
    return node_fn


def route_next(state: AgentState) -> str:
    """
    Decides the next execution node based on the current step in the execution plan.
    Enforces loop limit to prevent runaways.
    """
    if state.get("loop_count", 0) >= 10:
        logger.warning("[Router] Autonomous cycle limit (10) exceeded. Routing to response node.")
        return "response"

    plan = state.get("plan", [])
    current_step = state.get("current_step", 0)

    if not plan:
        logger.info("[Router] No plan found in state, routing to response node")
        return "response"

    if current_step >= len(plan):
        logger.info(f"[Router] Plan completed ({current_step}/{len(plan)} steps), routing to response node")
        return "response"

    next_step = plan[current_step]
    tool_name = next_step.get("tool", "direct_answer").lower()

    logger.info(f"[Router] Step {current_step + 1}/{len(plan)}: Routing to '{tool_name}'")

    if tool_name == "direct_answer":
        return "response"

    # Map tool name to corresponding graph node name
    tool_node_mapping = {
        "files": "files_node",
        "tasks": "tasks_node",
        "notes": "notes_node",
        "memory": "memory_node",
        "research": "research_node",
        "browser": "browser_node",
        "gmail": "gmail_node",
        "email": "gmail_node",
        "calendar": "calendar_node",
        "coding": "coding_node",
        "code": "coding_node",
        "github": "github_node",
        "voice": "voice_node",
    }

    dest = tool_node_mapping.get(tool_name)
    if dest:
        return dest

    logger.warning(f"[Router] Unknown tool: {tool_name}, falling back to response node")
    return "response"


def build_agent_graph() -> StateGraph:
    """
    Build and compile the multi-agent graph logic.
    """
    workflow = StateGraph(AgentState)

    # Register core control nodes
    workflow.add_node("memory", run_memory_node)
    workflow.add_node("planner", run_planner)
    workflow.add_node("evaluate", run_evaluate_node)
    workflow.add_node("replan", run_replan_node)
    workflow.add_node("response", run_response_node)

    # Register specialist sub-agent nodes
    workflow.add_node("files_node", make_agent_node(run_file_agent, "files"))
    workflow.add_node("tasks_node", make_agent_node(run_task_agent, "tasks"))
    workflow.add_node("notes_node", make_agent_node(run_notes_agent, "notes"))
    workflow.add_node("memory_node", make_agent_node(run_memory_agent, "memory"))
    workflow.add_node("research_node", make_agent_node(run_research_agent, "research"))
    workflow.add_node("browser_node", make_agent_node(run_browser_agent, "browser"))
    workflow.add_node("gmail_node", make_agent_node(run_gmail_agent, "gmail"))
    workflow.add_node("calendar_node", make_agent_node(run_calendar_agent, "calendar"))
    workflow.add_node("coding_node", make_agent_node(run_coding_agent, "coding"))
    workflow.add_node("github_node", make_agent_node(run_github_agent, "github"))
    workflow.add_node("voice_node", make_agent_node(run_voice_agent, "voice"))

    # Establish entry point
    workflow.set_entry_point("memory")

    # Connect simple transitions
    workflow.add_edge("memory", "planner")
    workflow.add_edge("replan", "planner")

    # Connect specialist nodes to evaluate node
    workflow.add_edge("files_node", "evaluate")
    workflow.add_edge("tasks_node", "evaluate")
    workflow.add_edge("notes_node", "evaluate")
    workflow.add_edge("memory_node", "evaluate")
    workflow.add_edge("research_node", "evaluate")
    workflow.add_edge("browser_node", "evaluate")
    workflow.add_edge("gmail_node", "evaluate")
    workflow.add_edge("calendar_node", "evaluate")
    workflow.add_edge("coding_node", "evaluate")
    workflow.add_edge("github_node", "evaluate")
    workflow.add_edge("voice_node", "evaluate")

    # Connect conditional routing edges from planner
    workflow.add_conditional_edges(
        "planner",
        route_next,
        {
            "files_node": "files_node",
            "tasks_node": "tasks_node",
            "notes_node": "notes_node",
            "memory_node": "memory_node",
            "research_node": "research_node",
            "browser_node": "browser_node",
            "gmail_node": "gmail_node",
            "calendar_node": "calendar_node",
            "coding_node": "coding_node",
            "github_node": "github_node",
            "voice_node": "voice_node",
            "response": "response",
        }
    )

    # Connect conditional routing edges from evaluate
    workflow.add_conditional_edges(
        "evaluate",
        route_evaluation,
        {
            "planner": "planner",
            "replan": "replan",
            "response": "response",
        }
    )

    # End point
    workflow.add_edge("response", END)

    return workflow


# Compiled graph singleton cache
_compiled_graph = None


def get_agent_graph():
    """Retrieve the compiled agent graph singleton."""
    global _compiled_graph
    if _compiled_graph is None:
        workflow = build_agent_graph()
        _compiled_graph = workflow.compile()
        logger.info("✅ Uday AI LangGraph agent compiled successfully.")
    return _compiled_graph
