"""
Uday AI — Tool Execution Node
"""

from __future__ import annotations

import logging
from langchain_core.messages import HumanMessage, AIMessage
from app.agents.state import AgentState

# Import existing working sub-agents
from app.agents.file_agent import run_file_agent
from app.agents.task_agent import run_task_agent
from app.agents.notes_agent import run_notes_agent
from app.agents.memory_agent import run_memory_agent
from app.agents.research_agent import run_research_agent
from app.agents.coding_agent import run_coding_agent
from app.agents.browser_agent import run_browser_agent
from app.agents.gmail_agent import run_gmail_agent
from app.agents.calendar_agent import run_calendar_agent
from app.agents.github_agent import run_github_agent
logger = logging.getLogger(__name__)


async def run_tools_node(state: AgentState) -> dict:
    """
    Unified Tool Execution Node.
    Executes the tool specified in the current step of the plan.
    Ensures sequential tracking and clean error boundaries.
    """
    plan = state.get("plan", [])
    current_step = state.get("current_step", 0)

    if not plan or current_step >= len(plan):
        logger.warning(f"[Tools Node] Invalid step index: {current_step}")
        return {"current_step": current_step + 1}

    step = plan[current_step]
    tool_name = step.get("tool", "").lower()
    argument = step.get("argument", "")

    from app.security.gates import requires_confirmation

    # Check if this tool execution requires confirmation and has not been approved yet
    if requires_confirmation(tool_name, argument) and not state.get("approved"):
        logger.info(f"[Tools Node] Intercepting '{tool_name}' for confirmation. Argument: '{argument}'")
        return {
            "approval_required": True
        }

    logger.info(f"[Tools Node] Executing step {current_step + 1}/{len(plan)}: '{tool_name}' with args: '{argument}'")

    # Inject the argument as a HumanMessage at the end of the history
    # so the sub-agents read the correct parameters
    injected_state = state.copy()
    injected_state["messages"] = list(state.get("messages", [])) + [HumanMessage(content=argument)]

    tool_results = state.get("tool_results", {}).copy()

    try:
        if tool_name == "files":
            result = await run_file_agent(injected_state)
        elif tool_name == "tasks":
            result = await run_task_agent(injected_state)
        elif tool_name == "notes":
            result = await run_notes_agent(injected_state)
        elif tool_name == "memory":
            result = await run_memory_agent(injected_state)
        elif tool_name == "research":
            result = await run_research_agent(injected_state)
        elif tool_name == "browser":
            result = await run_browser_agent(injected_state)
        elif tool_name == "gmail" or tool_name == "email":
            result = await run_gmail_agent(injected_state)
        elif tool_name == "calendar":
            result = await run_calendar_agent(injected_state)
        elif tool_name == "code" or tool_name == "coding":
            result = await run_coding_agent(injected_state)
        elif tool_name == "github":
            result = await run_github_agent(injected_state)
        elif tool_name == "whatsapp":
            from app.agents.whatsapp_agent import run_whatsapp_agent
            result = await run_whatsapp_agent(injected_state)
        elif tool_name == "voice":
            # Direct response for voice control triggers
            result = {
                "final_response": f"Voice system command executed: {argument}",
                "messages": [AIMessage(content=f"Voice system command executed: {argument}")]
            }
        else:
            raise ValueError(f"Unknown tool name: {tool_name}")

        # Store tool output
        tool_results[tool_name] = result.get("final_response", "")

        # Extract messages generated by the tool
        new_messages = result.get("messages", [])

        # Merge results back into the state updates
        updates = {
            "current_step": current_step + 1,
            "tool_results": tool_results,
            "approved": False,
            "approval_required": False,
            "agent_results": {
                **state.get("agent_results", {}),
                **result.get("agent_results", {})
            }
        }
        if new_messages:
            updates["messages"] = new_messages

        return updates

    except Exception as e:
        logger.error(f"[Tools Node] Error executing tool '{tool_name}': {e}", exc_info=True)
        tool_results[tool_name] = f"Error: {str(e)}"
        return {
            "current_step": current_step + 1,
            "tool_results": tool_results,
            "approved": False,
            "approval_required": False,
            "error": f"Tool '{tool_name}' failed: {str(e)}"
        }


# ── Evaluation & Replanning Nodes ──────────────────────────────────────

from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage

class ReplanStep(BaseModel):
    step_number: int = Field(description="Step number (1-based, starting from the current step)")
    tool: str = Field(description="The tool to execute. Must be one of: files, tasks, notes, voice, memory, research, direct_answer")
    argument: str = Field(description="Parameters or search queries for the tool execution")

class ReplannerOutput(BaseModel):
    plan: list[ReplanStep] = Field(description="New remaining steps to execute")
    reasoning: str = Field(description="Reasoning log behind the re-formulated plan")

REPLANNER_SYSTEM_PROMPT = """You are the **Replanning Agent** for Uday AI, a personal AI Operating System.
An error occurred during the execution of step {step_number} in the plan.

Original Query: {query}
Previous Plan: {plan}
Tool Results: {tool_results}
Error: {error}

Your task is to re-evaluate the plan and construct a new, corrected sequence of steps starting from step {step_number} to solve the user's request.
You can modify the remaining steps, choose different tools, or add steps.
Available Tools:
1. `files` - Search, upload, query PDFs/text documents (RAG). Use when files/documents are referenced.
2. `tasks` - Create, update, view todo list items. Use for todos, tasks, goals.
3. `notes` - Create, view, search, modify personal memos. Use for quick text notes.
4. `voice` - STT transcription or TTS synthesis queries.
5. `memory` - Fetch specific facts, preferences, or recall user relationships.
6. `direct_answer` - Use when the request is conversational and requires no tools.
7. `research` - Web search, multi-source research, summarization, fact verification.

Formulate an updated, corrected sequence of remaining steps to solve the user's request.
"""

async def run_evaluate_node(state: AgentState) -> dict:
    """
    Evaluates the tool execution outcome.
    """
    if state.get("approval_required"):
        return {"evaluation_result": "approval_required"}
        
    if state.get("error"):
        return {"evaluation_result": "failure"}
        
    return {"evaluation_result": "success"}

def route_evaluation(state: AgentState) -> str:
    """
    Routes after evaluation.
    """
    res = state.get("evaluation_result", "success")
    if res == "approval_required":
        return "response"
    elif res == "failure":
        return "replan"
    return "planner"

async def run_replan_node(state: AgentState) -> dict:
    """
    Run the replanning node when a tool error is encountered.
    Updates the remaining plan queue.
    """
    from app.llm.provider import get_llm
    import json

    plan = state.get("plan", [])
    current_step = state.get("current_step", 0)
    user_msg = state.get("user_message", "")
    error = state.get("error", "Unknown error")
    tool_results = state.get("tool_results", {})
    
    logger.info(f"[Replanner] Replanning for step {current_step + 1} due to error: {error}")
    
    llm = get_llm(temperature=0.1)
    
    system_prompt = REPLANNER_SYSTEM_PROMPT.format(
        step_number=current_step + 1,
        query=user_msg,
        plan=json.dumps(plan),
        tool_results=json.dumps(tool_results),
        error=error
    )
    
    try:
        structured_llm = llm.with_structured_output(ReplannerOutput)
        res = await structured_llm.ainvoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content="Please adjust the plan to handle the failure.")
        ])
        
        new_steps = [
            {"step_number": s.step_number, "tool": s.tool, "argument": s.argument}
            for s in res.plan
        ]
        reasoning = res.reasoning
        
    except Exception as e:
        logger.warning(f"[Replanner] Structured output failed: {e}. Using fallback parser.")
        # Fallback to direct answer if replanning fails
        new_steps = [{"step_number": current_step + 1, "tool": "direct_answer", "argument": f"I encountered an error trying to process your request: {error}"}]
        reasoning = "Fallback replan due to model parsing issues."
        
    # Replace plan from current_step onwards
    updated_plan = plan[:current_step] + new_steps
    
    logger.info(f"[Replanner] New plan formulated: {updated_plan} (Reasoning: {reasoning})")
    
    return {
        "plan": updated_plan,
        "error": None, # Clear the error to allow execution to proceed
        "metadata": {
            **state.get("metadata", {}),
            "replanner_reasoning": reasoning
        }
    }
